
---
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: QwietPoC

on:
  pull_request:
  workflow_dispatch:
jobs:
  NextGen-Static-Analysis:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    # We are building this application with Java 11
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    #- name: Package with maven
    #  run: mvn clean package
    - name: Download ShiftLeft CLI
      run: |
        Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile ${GITHUB_WORKSPACE}\sl.zip
          Expand-Archive -Path ${GITHUB_WORKSPACE}\sl.zip -DestinationPath ${GITHUB_WORKSPACE}\
    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl.exe analyze --strict --wait --verbose --app JavaTestGH
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_HOST: www.shiftleft.io
        SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
        SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443
